version: '3.9'

services:
  database:
    container_name: sfhacks_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - sfhacks-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
  memcached:
    container_name: sfhacks-memcached
    image: memcached
    ports:
      - 11211:11211
  migration:
    container_name: migration
    build: ./backend
    command: alembic upgrade head
    env_file:
      - backend.env
    depends_on:
      database:
        condition: service_healthy
  dispatcher:
    container_name: sfhacks_dispatcher
    build: ./dispatcher
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file:
      - dispatcher.env
  backend:
    container_name: sfhacks_backend
    build: ./backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file:
      - backend.env
    volumes:
      - ./backend/gcs.json:/app/gcs.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
  control_frontend:
    container_name: sfhacks_control_frontend
    build: 
      context: ./control-frontend
      args:
        - VITE_BACKEND_URL=http://localhost:8000
    restart: always
    depends_on:
      backend:
        condition: service_healthy
  instance_frontend:
    container_name: sfhacks_instance_frontend
    build: 
      context: ./instance-frontend
      args:
        - VITE_BACKEND_URL=http://localhost:8000
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    
volumes:
  sfhacks-db-volume:
    