# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build-backend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
      
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v2'

#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
      
#       - name: Configure Docker to use the gcloud command-line tool as a credential helper
#         run: gcloud auth configure-docker us-west3-docker.pkg.dev --quiet

#       - name: Build Backend Docker Image
#         run: |
#           cd backend
#           docker build . -t us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-backend:${{ github.sha }}
          
#       - name: Push Backend Docker Image to Google Artifact Registry
#         run: |
#           docker push us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-backend:${{ github.sha }}

#   build-instance-frontend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
      
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v2'

#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
      
#       - name: Configure Docker to use the gcloud command-line tool as a credential helper
#         run: gcloud auth configure-docker us-west3-docker.pkg.dev --quiet

#       - name: Build Instance Frontend Docker Image
#         run: |
#           cd instance-frontend
#           docker build --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} . -t us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-instance-frontend:${{ github.sha }}
          
#       - name: Push Instance Frontend Docker Image to Google Artifact Registry
#         run: |
#           docker push us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-instance-frontend:${{ github.sha }}

#   build-control-frontend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
      
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v2'

#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
      
#       - name: Configure Docker to use the gcloud command-line tool as a credential helper
#         run: gcloud auth configure-docker us-west3-docker.pkg.dev --quiet

#       - name: Build Control Frontend Docker Image
#         run: |
#           cd control-frontend
#           docker build --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} . -t us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-control-frontend:${{ github.sha }}
          
#       - name: Push Control Frontend Docker Image to Google Artifact Registry
#         run: |
#           docker push us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-control-frontend:${{ github.sha }}

#   build-dispatcher:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
      
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v2'

#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
      
#       - name: Configure Docker to use the gcloud command-line tool as a credential helper
#         run: gcloud auth configure-docker us-west3-docker.pkg.dev --quiet

#       - name: Build Dispatcher Docker Image
#         run: |
#           cd dispatcher
#           docker build . -t us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-dispatcher:${{ github.sha }}
          
#       - name: Push Dispatcher Docker Image to Google Artifact Registry
#         run: |
#           docker push us-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sfhacks-registry/sfhacks-dispatcher:${{ github.sha }}
